workflows:
  ionic-ios-workflow:
    name: Ionic iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      node: 18
      npm: latest
      cocoapods: default
      xcode: latest
      vars:
        IONIC_CLI_VERSION: "7.1.1"
    scripts:
      - name: Install dependencies
        script: |
          npm install -g @ionic/cli@$IONIC_CLI_VERSION
          npm ci
      - name: Cocoapods installation
        script: |
          cd ios/App && pod install
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build iOS
        script: |
          ionic build
          ionic cap copy ios
          ionic cap build ios --prod
    artifacts:
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM